import { createClient } from 'npm:@supabase/supabase-js@2.39.7';
import { Configuration, OpenAIApi } from 'npm:openai@4.28.0';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
  'Access-Control-Allow-Methods': 'POST, OPTIONS',
  'Content-Type': 'application/json'
};

Deno.serve(async (req) => {
  // Handle CORS
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { submissionId } = await req.json();

    if (!submissionId) {
      throw new Error('Submission ID is required');
    }

    // Validate environment variables
    const openaiKey = Deno.env.get('OPEN_API_KEY'); // Updated to match your secret name
    if (!openaiKey) {
      console.error('OPEN_API_KEY is missing');
      throw new Error('Configuration error: OpenAI API key is not set');
    }

    // Create Supabase client
    const supabaseAdmin = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? ''
    );

    // Fetch the submission
    const { data: submission, error: fetchError } = await supabaseAdmin
      .from('quiz_submissions')
      .select('*')
      .eq('id', submissionId)
      .single();

    if (fetchError) {
      console.error('Error fetching submission:', fetchError);
      throw new Error('Failed to fetch submission');
    }

    if (!submission) {
      throw new Error('Submission not found');
    }

    // Check if answers exist
    if (!submission.answer_1 && !submission.answer_2 && !submission.answer_3) {
      throw new Error('No answers found in submission');
    }

    const configuration = new Configuration({
      apiKey: openaiKey
    });
    const openai = new OpenAIApi(configuration);

    const analysisPrompt = `
      En tant qu'expert en prompt engineering, analysez ces réponses de quiz et fournissez une évaluation détaillée en français.
      
      Pour chaque réponse :
      1. Donnez une note sur 10
      2. Expliquez les points forts et les points à améliorer
      3. Donnez des suggestions d'amélioration concrètes
      
      Question 1: Transformer ce mauvais prompt "Je veux améliorer les ventes"
      Réponse: "${submission.answer_1 || 'Non répondu'}"

      Question 2: Créer un prompt pour votre pôle spécifique
      Réponse: "${submission.answer_2 || 'Non répondu'}"

      Question 3: Identifier les erreurs dans "Fais quelque chose de bien pour mon équipe qui soit original et utile"
      Réponse: "${submission.answer_3 || 'Non répondu'}"

      Évaluez selon ces critères :
      - Utilisation du modèle universel
      - Précision du contexte
      - Clarté des objectifs
      - Pertinence des contraintes
      - Qualité globale du prompt

      À la fin, donnez une évaluation globale du niveau :
      - Novice : Comprend les bases mais nécessite plus de pratique
      - Intermédiaire : Bonne maîtrise des concepts fondamentaux
      - Avancé : Excellente compréhension et application
      - Expert : Maîtrise exceptionnelle et créativité
      - Illuminé : Niveau remarquable, innovation et excellence

      Format de réponse souhaité :
      Question 1 :
      Note : X/10
      Points forts :
      - ...
      Points à améliorer :
      - ...
      Suggestions :
      - ...

      [Répéter pour questions 2 et 3]

      Niveau global : [niveau] - [justification détaillée]
    `;

    console.log('Sending request to OpenAI...');
    const completion = await openai.createChatCompletion({
      model: "gpt-4",
      messages: [
        {
          role: "system",
          content: "Vous êtes un expert en prompt engineering qui évalue les compétences des apprenants. Vos analyses sont constructives, détaillées et encourageantes."
        },
        {
          role: "user",
          content: analysisPrompt
        }
      ],
      temperature: 0.7,
      max_tokens: 2000
    });

    if (!completion.data.choices[0]?.message?.content) {
      throw new Error('No analysis generated by OpenAI');
    }

    const analysis = completion.data.choices[0].message.content;
    console.log('Received response from OpenAI');

    // Store the analysis in the database
    const { error: updateError } = await supabaseAdmin
      .from('quiz_submissions')
      .update({ analysis })
      .eq('id', submissionId);

    if (updateError) {
      console.error('Error updating submission:', updateError);
      throw new Error('Failed to save analysis');
    }

    return new Response(
      JSON.stringify({ 
        success: true,
        analysis 
      }),
      { headers: corsHeaders }
    );
  } catch (error) {
    console.error('Analysis error:', error);
    return new Response(
      JSON.stringify({ 
        success: false,
        error: error.message,
        details: 'An error occurred during quiz analysis'
      }),
      { 
        headers: corsHeaders,
        status: 500
      }
    );
  }
});